services:
  master:
    image: example/master
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    # entrypoint: sleep
    # command: infinity
    command: -l -k -p 8080 | tee -a /dev/stdout"

  worker:
    image: example/worker
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: sleep
    command: infinity
